// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/pusrenk/customer-service/internal/customers/entitites"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerService creates a new instance of MockCustomerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerService {
	mock := &MockCustomerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerService is an autogenerated mock type for the CustomerService type
type MockCustomerService struct {
	mock.Mock
}

type MockCustomerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerService) EXPECT() *MockCustomerService_Expecter {
	return &MockCustomerService_Expecter{mock: &_m.Mock}
}

// CreateCustomer provides a mock function for the type MockCustomerService
func (_mock *MockCustomerService) CreateCustomer(customer *entitites.Customer) error {
	ret := _mock.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entitites.Customer) error); ok {
		r0 = returnFunc(customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerService_CreateCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCustomer'
type MockCustomerService_CreateCustomer_Call struct {
	*mock.Call
}

// CreateCustomer is a helper method to define mock.On call
//   - customer *entitites.Customer
func (_e *MockCustomerService_Expecter) CreateCustomer(customer interface{}) *MockCustomerService_CreateCustomer_Call {
	return &MockCustomerService_CreateCustomer_Call{Call: _e.mock.On("CreateCustomer", customer)}
}

func (_c *MockCustomerService_CreateCustomer_Call) Run(run func(customer *entitites.Customer)) *MockCustomerService_CreateCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entitites.Customer
		if args[0] != nil {
			arg0 = args[0].(*entitites.Customer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerService_CreateCustomer_Call) Return(err error) *MockCustomerService_CreateCustomer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerService_CreateCustomer_Call) RunAndReturn(run func(customer *entitites.Customer) error) *MockCustomerService_CreateCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCustomer provides a mock function for the type MockCustomerService
func (_mock *MockCustomerService) DeleteCustomer(id uint) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCustomer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerService_DeleteCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCustomer'
type MockCustomerService_DeleteCustomer_Call struct {
	*mock.Call
}

// DeleteCustomer is a helper method to define mock.On call
//   - id uint
func (_e *MockCustomerService_Expecter) DeleteCustomer(id interface{}) *MockCustomerService_DeleteCustomer_Call {
	return &MockCustomerService_DeleteCustomer_Call{Call: _e.mock.On("DeleteCustomer", id)}
}

func (_c *MockCustomerService_DeleteCustomer_Call) Run(run func(id uint)) *MockCustomerService_DeleteCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerService_DeleteCustomer_Call) Return(err error) *MockCustomerService_DeleteCustomer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerService_DeleteCustomer_Call) RunAndReturn(run func(id uint) error) *MockCustomerService_DeleteCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCustomers provides a mock function for the type MockCustomerService
func (_mock *MockCustomerService) GetAllCustomers() ([]*entitites.Customer, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllCustomers")
	}

	var r0 []*entitites.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*entitites.Customer, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*entitites.Customer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entitites.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerService_GetAllCustomers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCustomers'
type MockCustomerService_GetAllCustomers_Call struct {
	*mock.Call
}

// GetAllCustomers is a helper method to define mock.On call
func (_e *MockCustomerService_Expecter) GetAllCustomers() *MockCustomerService_GetAllCustomers_Call {
	return &MockCustomerService_GetAllCustomers_Call{Call: _e.mock.On("GetAllCustomers")}
}

func (_c *MockCustomerService_GetAllCustomers_Call) Run(run func()) *MockCustomerService_GetAllCustomers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCustomerService_GetAllCustomers_Call) Return(customers []*entitites.Customer, err error) *MockCustomerService_GetAllCustomers_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *MockCustomerService_GetAllCustomers_Call) RunAndReturn(run func() ([]*entitites.Customer, error)) *MockCustomerService_GetAllCustomers_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerByID provides a mock function for the type MockCustomerService
func (_mock *MockCustomerService) GetCustomerByID(id uint) (*entitites.Customer, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByID")
	}

	var r0 *entitites.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint) (*entitites.Customer, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint) *entitites.Customer); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entitites.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerService_GetCustomerByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerByID'
type MockCustomerService_GetCustomerByID_Call struct {
	*mock.Call
}

// GetCustomerByID is a helper method to define mock.On call
//   - id uint
func (_e *MockCustomerService_Expecter) GetCustomerByID(id interface{}) *MockCustomerService_GetCustomerByID_Call {
	return &MockCustomerService_GetCustomerByID_Call{Call: _e.mock.On("GetCustomerByID", id)}
}

func (_c *MockCustomerService_GetCustomerByID_Call) Run(run func(id uint)) *MockCustomerService_GetCustomerByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerService_GetCustomerByID_Call) Return(customer *entitites.Customer, err error) *MockCustomerService_GetCustomerByID_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerService_GetCustomerByID_Call) RunAndReturn(run func(id uint) (*entitites.Customer, error)) *MockCustomerService_GetCustomerByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCustomer provides a mock function for the type MockCustomerService
func (_mock *MockCustomerService) UpdateCustomer(customer *entitites.Customer) error {
	ret := _mock.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*entitites.Customer) error); ok {
		r0 = returnFunc(customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerService_UpdateCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCustomer'
type MockCustomerService_UpdateCustomer_Call struct {
	*mock.Call
}

// UpdateCustomer is a helper method to define mock.On call
//   - customer *entitites.Customer
func (_e *MockCustomerService_Expecter) UpdateCustomer(customer interface{}) *MockCustomerService_UpdateCustomer_Call {
	return &MockCustomerService_UpdateCustomer_Call{Call: _e.mock.On("UpdateCustomer", customer)}
}

func (_c *MockCustomerService_UpdateCustomer_Call) Run(run func(customer *entitites.Customer)) *MockCustomerService_UpdateCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entitites.Customer
		if args[0] != nil {
			arg0 = args[0].(*entitites.Customer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerService_UpdateCustomer_Call) Return(err error) *MockCustomerService_UpdateCustomer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerService_UpdateCustomer_Call) RunAndReturn(run func(customer *entitites.Customer) error) *MockCustomerService_UpdateCustomer_Call {
	_c.Call.Return(run)
	return _c
}
